### ISSUE TITLE
Create a datapackage JSON file for each dataset

### ISSUE THREAD

**Issue by cindyli** [inclusive-design/covid-assessment-centres#12]
Create a datapackage JSON file for each dataset in different data directories. This file will provide basic information such as the purpose of the dataset, where the data comes from etc.

The information about the data package JSON file can be found at https://frictionlessdata.io/data-package/#datapackage-json

**Comment by ritikramuka** [comment]
I would like to work on this issue, so can you guide me little to how to do as this my first time contributing to open source

**Comment by cindyli** [comment]
> I would like to work on this issue, so can you guide me little to how to do as this my first time contributing to open source

Thanks for your interest, @ritikramuka. There's already a pull request to cover this issue: https://github.com/inclusive-design/covid-assessment-centres/pull/13

**Comment by cindyli** [comment]
Resolved with the merge of https://github.com/inclusive-design/covid-assessment-centres/pull/13

**Comment by ritikramuka** [comment]
@cindyli I'm interested to work on this project so can you open me to some beginner friendly issues for a start

**Comment by cindyli** [comment]
Thanks for your interest in the project, @ritikramuka. I will keep this in mind and ping you when a beginner issue is available.
