### ISSUE TITLE
Automatically commit new versions of the data.ontario.ca dataset

### ISSUE THREAD

**Issue by hex-for-hecate** [inclusive-design/covid-assessment-centres#5]
We should make it easy to manually or automatically pull in new versions of the dataset provided by the Ontairo Data Catalogue. It seems reasonable to distribute the means of doing this with the data repository itself. 

The first iteration of this solution is a node script that interfaces with data.ontario.ca, a local clone of this repository, and the GitHub remote. Further iterations should focus on making it run automatically, e.g. on a rented server.

**Comment by cindyli** [comment]
Closed as this issue has been moved to https://github.com/inclusive-design/data-update-github/issues/1
